apiVersion: v1
kind: ConfigMap
metadata:
  name: myvalues
  namespace: default
data:
  keyvaultname: "secretmanagementsprint"
  testlabel: "helloworld-one"
  version: "v1"
  tenantid: "cfd26b50-fb8f-44cf-87b2-d5df3d15d884"
