apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-ns  
  namespace: default
spec:
  interval: 1m  
  prune: true
  path: "./"
  sourceRef:
    kind: GitRepository
    name: gitcust 
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: myvalues
