apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-ns
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ${keyvaultname}
    objects:  |
      array:
        - |
          objectName: testSecret
          objectType: secret             
          objectVersion: ""
        - |
          objectName: testSecret2
          objectType: secret             
          objectVersion: ""
        - |
          objectName: testSecret3
          objectType: secret             
          objectVersion: ""      
        - |
          objectName: testSecret4
          objectType: secret             
          objectVersion: "" 
    tenantId: ${tenantid} 
