apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myhelmrelease
  namespace: default
...
spec:
  values:
      customMetadata:    # Experiment with adding quotes multiple ways.
        - name: keyvault
          value: "${keyvault}" 
