apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 1m
  path: "./apps/"
  sourceRef:
    kind: GitRepository
    name: gitfolder 
  postBuild:
    substitute:
      cluster_env: "prod"
      cluster_region: "eu-central-1"
